name: flexora
description: "A Flutter platform for adaptive business management."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.1.0
  dio: ^5.4.0
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/flexora_icon.png
    - assets/icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/flexora_icon.png"
  adaptive_icon_background: "#0F0F0F"
  adaptive_icon_foreground: "assets/flexora_icon.png"